name: C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache vcpkg archives
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/vcpkg/archives
            ~\AppData\Local\vcpkg\archives
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Set up CMake
        uses: lukka/get-cmake@v3

      - name: Install vcpkg
        shell: pwsh
        run: |
          $repo = Join-Path $env:RUNNER_TEMP 'vcpkg'
          if (!(Test-Path $repo)) { git clone https://github.com/microsoft/vcpkg $repo }
          if ($IsWindows) {
            & (Join-Path $repo 'bootstrap-vcpkg.bat') -disableMetrics
          } else {
            bash (Join-Path $repo 'bootstrap-vcpkg.sh') -disableMetrics
          }

      - name: Configure
        shell: pwsh
        run: cmake --preset msvc-debug

      - name: Build
        shell: pwsh
        run: cmake --build --preset build --parallel

      - name: Test
        shell: pwsh
        run: ctest --preset test --output-on-failure
